reservation_index:
    path:     /
    defaults: { _controller: "MyAppUserBundle:reservation:index" }
    methods:  GET

reservation_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppUserBundle:reservation:show" }
    methods:  GET

reservation_new:
    path:     /new
    defaults: { _controller: "MyAppUserBundle:reservation:new" }
    methods:  [GET, POST]

reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppUserBundle:reservation:edit" }
    methods:  [GET, POST]

reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppUserBundle:reservation:delete" }
    methods:  DELETE
